services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_playground
    ports:
      - "6333:6333"   # REST API
#      - "6334:6334"   # gRPC (hozircha kerak emas)
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

volumes:
  qdrant_data:
