services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant_playground
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: unless-stopped

  api:
    build: .
    container_name: fastapi_mvp_api
    env_file:
      - .env
    ports:
      - "8099:8099"
    volumes:
      - ./:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

volumes:
  qdrant_data:
